SCENARIOS = {
    "Lost Hiker in Forest": {
        "subject_name": "Daniel Carter",
        "age": 27,
        "status_type": "Hiker",
        "hours_missing": 7.5,
        "last_seen_location": "North trailhead near ranger cabin",
        "weather": "Fog",
        "temperature_f": 46,
        "terrain": "Forest",
        "mobility_level": "High",
        "medical_risk": "Medium",
        "has_phone": True,
        "phone_battery": 34,
        "wearable_detected": False,
        "stress_level": "Medium",
        "notes": "Experienced hiker, missed sunset check-in, may have attempted shortcut route.",
    },
    "Missing Child Near Park": {
        "subject_name": "Emma Lewis",
        "age": 8,
        "status_type": "Child",
        "hours_missing": 2.0,
        "last_seen_location": "Playground edge by parking lot",
        "weather": "Clear",
        "temperature_f": 72,
        "terrain": "Urban Edge",
        "mobility_level": "Low",
        "medical_risk": "High",
        "has_phone": False,
        "phone_battery": 0,
        "wearable_detected": True,
        "stress_level": "High",
        "notes": "Subject is shy, may hide when frightened, responds well to familiar voice.",
    },
    "Disaster Victim After Storm": {
        "subject_name": "Maria Ortiz",
        "age": 41,
        "status_type": "Disaster Victim",
        "hours_missing": 14.0,
        "last_seen_location": "Flooded roadside shelter",
        "weather": "Rain",
        "temperature_f": 51,
        "terrain": "Lake / Trail",
        "mobility_level": "Low",
        "medical_risk": "High",
        "has_phone": True,
        "phone_battery": 67,
        "wearable_detected": False,
        "stress_level": "High",
        "notes": "Subject may be injured and seeking cover rather than moving long distances.",
    },
}
